.TH MYCAT 1 "September 2025" "Version 1.0" "User Commands"
.SH NAME
mycat \- display the contents of a file
.SH SYNOPSIS
mycat [filename]
.SH DESCRIPTION
The mycat function reads the contents of the specified file and 
prints it to the standard output.
.SH AUTHOR
Amos Shehzad <lukkygill26@gmail.com>
